env:
  - GO111MODULE=on
  - CGO_ENABLED=0
  - RELEASE_BUILDS=dist/tiltify_darwin_amd64/tiltify dist/tiltify_linux_amd64/tiltify dist/tiltify_windows_amd64/tiltify.exe

builds:
  - binary: tiltify
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X "main.buildVersion={{ .Tag }} ({{ .ShortCommit }} {{ .Date }})"
    hooks:
      # stuff executables with static assets.
      post: make pack-releases

archives:
  - format: tar.gz
    files:
      - README.md
      - LICENSE

snapcrafts:
  - name_template: '{{ .ProjectName }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    summary: Templating tool for scaffolding Tilt configuration file.
    description: |
      tiltify lets you quickly create a tilt configuration for Kubernetes resources.
    grade: stable
    confinement: strict
    publish: true
